platform :ios, '10.0'

use_frameworks!
target 'AEPSampleExtension' do
    pod 'AEPServices', :git => 'git@github.com:shalehaha/aepsdk-core-ios.git', :branch => 'cocoapod'
    pod 'AEPEventhub', :git => 'git@github.com:shalehaha/aepsdk-core-ios.git', :branch => 'cocoapod'
    pod 'SwiftRulesEngine', :git => 'git@github.com:shalehaha/aepsdk-rulesengine-ios.git', :branch => 'dev'
end

