platform :ios, '10.0'

use_frameworks!
target 'AEPSampleExtension' do
    pod 'AEPServices', :git => 'git@github.com:shalehaha/aepsdk-core-ios.git', :branch => 'make'
    pod 'AEPEventHub', :git => 'git@github.com:shalehaha/aepsdk-core-ios.git', :branch => 'make'
    pod 'SwiftRulesEngine', :git => 'git@github.com:shalehaha/aepsdk-rulesengine-ios.git', :branch => 'dev'
end

